// The combat round: a shared Player Turn, then an Enemy Turn, repeating.
//
// Every exported function takes a state and returns a new one. An illegal
// action returns the SAME REFERENCE, which is how callers and the server tell
// "not allowed" from "allowed but nothing changed".

export { chooseEndTurnTarget, defaultEndTurnOrder, endTurnChoiceId, endTurnChoiceTarget } from './combat/types.ts'
export type {
  CardChoicePreview,
  CombatPhase,
  CombatPresentationEvent,
  CombatState,
  DiscardOrders,
  EndTurnAbility,
  EndTurnOrder,
  EvokeChoice,
  PendingTrigger,
  PendingTriggerAbility,
  PlayedCard,
  PlayContext,
  PotionContext,
  PowerContext,
  RelicContext,
  StartTurnAbility,
  StartTurnChoice,
  StartTurnDiscardPreview,
  StartTurnScryAbility,
  StartTurnScryPreview,
} from './combat/types.ts'
export {
  combatRowLabel,
  enemyLabel,
  lightningRowFromTarget,
  lightningRowTarget,
  lightningTargetsRows,
  livingEnemies,
  powerAbilityKey,
  powerAbilityUsed,
  remainingRoundHpLoss,
  resolveEnemyTargets,
} from './combat/board.ts'
export {
  cardEnemyChoiceCount,
  cardHasRetain,
  cardIsPlayable,
  cardModeIsAvailable,
  cardNeedsChoicePreview,
  cardNeedsEnemy,
  cardPlayConditionMet,
  cardPlayerChoiceCount,
  cardReferencesGuardianMode,
  cardShivChoiceCount,
  chosenEvokeOrbs,
  effectIsActive,
  effectiveCombatCardDef,
  guardianPowerBeamCards,
  guardianGemForCard,
  guardianCardNeedsAlly,
  amountOf,
  activePowerWindow,
  nextEvokeChoice,
  mandatoryChoicePending,
  maximumXEnergy,
  overflowShivCount,
  playCost,
  reachesEnemy,
  reachedTimeWarpLimit,
  slimeChoiceIsAvailable,
  slimeCommandEnemyChoiceLabels,
  slimeCommandEnemyChoiceCount,
} from './combat/queries.ts'
export {
  MAX_TRIGGER_DEPTH,
  evokeTargetProgress,
  pendingTriggerSlimeEnemyChoiceLabels,
  pendingTriggerSlimeEnemyChoiceCount,
} from './combat/effects.ts'
export {
  abandonHermitChamberPlay,
  abandonHermitSetupLoad,
  abandonCardCopy,
  abandonForcedCard,
  activatePower,
  playCard,
  playCardCopy,
  playHermitChamberCard,
  previewCardChoice,
  previewCardCopyChoice,
  previewHermitChamberCardChoice,
  previewPowerChoice,
  resolveHermitSetupLoad,
  resolveHermitStrengthReward,
} from './combat/play.ts'
export {
  defaultPendingDieRelicChoice,
  defaultStartTurnChoices,
  facingChoicesAreValid,
  hasPostRollStartTurnChoice,
  orderStartTurnScries,
  preparePlayerTurn,
  preparePlayerTurnThroughDraw,
  resumePlayerTurnAfterDraw,
  resolvePendingDieRelicChoice,
  resolveStartPlayerTurn,
  resolveStartTurnDiscard,
  resolveStartTurnScry,
  startPlayerTurn,
  startPlayerTurnWithChoices,
  startTurnAbilities,
  startTurnDiscardPreview,
  startTurnNeedsChoice,
  startTurnScryAbilities,
  startTurnScryPreview,
} from './combat/start-turn.ts'
export {
  beginEndTurnResolution,
  beginEndPlayerTurn,
  discardNeedsChoice,
  discardOrderIsValid,
  endPlayerTurn,
  endTurnResolutionAbility,
  endTurnAbilities,
  pendingTriggerAbility,
  resolveEndTurnAbility,
  resolvePendingTrigger,
  validEndTurnOrder,
} from './combat/end-turn.ts'
export { enemyActingOrder, enemyTurn } from './combat/enemy-turn.ts'
export {
  activatePotion,
  activateRelic,
  canActivatePotion,
  canActivateRelic,
  chooseDistilledCard,
  spendMiracle,
  spendSoulburn,
  spendShiv,
  resolvePlunderRowSwitch,
} from './combat/items.ts'
export { createCombat } from './combat/create.ts'
