"""Bake the audited Sunburst drawings without morphing limbs or scaling bodies.

Run from any directory with python3 scripts/animation/kratos.py.
Pass --check to verify the generated CSS and timing constants without writing anything.
Native alpha stays intact; registration.json supplies inspected head landmarks and the clock.
"""
import json
import math
import re
import statistics
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
REG = json.loads((ROOT / 'scripts/animation/sources/kratos/combo-v3/registration.json').read_text())
OUT = ROOT / 'public/assets/combat/characters'
CSS = ROOT / 'src/ui/styles/attack-timing.css'
VFX = ROOT / 'src/ui/combat-screen/vfx.tsx'
SIZE = REG['runtimeCanvas']
CSS_START = '/* kratos-combo: generated by scripts/animation/kratos.py */'
CSS_END = '/* end kratos-combo */'
TS_START = '// kratos-timing: generated by scripts/animation/kratos.py'
TS_END = '// end kratos-timing'
# Head landmarks alone let a drawing with a small head inflate the whole body, so each
# combo-v3 drawing is also measured by its planted rear sole against the median rear sole
# of the kept combo-v2 drawings. The image model draws slightly smaller heads in dynamic
# poses, so the two scales may disagree by up to 20% and the geometric mean splits it.
SCALE_AGREEMENT = (.8, 1.2)
SOLE_BAND = 22


def solid_box(image):
    return image.getchannel('A').point(lambda a: 255 if a > 32 else 0).getbbox()


def foot_runs(image, box, height):
    """Solid column runs touching the ground band, left to right."""
    band = image.getchannel('A').point(lambda a: 255 if a > 64 else 0).crop((box[0], box[3] - height, box[2], box[3]))
    columns = [x for x in range(band.width) if band.crop((x, 0, x + 1, band.height)).getbbox()]
    runs = []
    for x in columns:
        if runs and x - runs[-1][1] <= 6:
            runs[-1][1] = x
        else:
            runs.append([x, x])
    return [(box[0] + a, box[0] + b) for a, b in runs]


def sole_width(image):
    first = foot_runs(image, solid_box(image), SOLE_BAND)[0]
    return first[1] - first[0] + 1


def resized(image, scale):
    return image.resize((round(image.width * scale), round(image.height * scale)), Image.Resampling.LANCZOS)


def trim_chain(image, trim):
    """Shorten a straight thrown chain by whole links so every hit lands on one blade line.

    Everything right of `x` is the chain and its blade alone; the strip of `length` source
    pixels after `x` is removed and the blade end slides back along the chain's slope.
    """
    cut, length = trim['x'], trim['length']
    strip = image.getchannel('A').point(lambda a: 255 if a > 128 else 0).crop((cut, 0, cut + length, image.height))
    heights = [sum(1 for v in strip.crop((x, 0, x + 1, strip.height)).get_flattened_data() if v) for x in range(length)]
    assert max(heights) <= 24, f'chainTrim strip at x={cut} holds more than a chain'
    out = Image.new('RGBA', image.size)
    out.alpha_composite(image.crop((0, 0, cut, image.height)))
    out.alpha_composite(image.crop((cut + length, 0, image.width, image.height)),
                        (cut, -round(length * trim['slope'])))
    return out


def place(name, kept_sole=None):
    """One uniform scale per drawing; returns the frame, rear-foot centre, rear-sole width and reach."""
    mark = REG['poses'][name]
    source = Image.open(ROOT / mark['source']).convert('RGBA')
    if 'chainTrim' in mark:
        source = trim_chain(source, mark['chainTrim'])
    if 'skull' in mark:
        # Original combo-v2 drawings: crown-to-jaw skull landmark, stance centred on the canvas.
        scale = REG['skullPixels'] / (mark['skull'][1] - mark['skull'][0])
        x, y = SIZE / 2 - mark['stanceCenter'] * scale, REG['ground'] - mark['foot'] * scale
    else:
        # Combo-v3 drawings: the geometric mean of the head and planted-sole scales.
        head_scale = REG['headPixels'] / (mark['head'][1] - mark['head'][0])
        agreement = kept_sole / sole_width(resized(source, head_scale))
        low, high = SCALE_AGREEMENT
        assert low <= agreement <= high, f'{name}: head and sole disagree on body scale ({agreement:.2f})'
        scale = head_scale * math.sqrt(agreement)
    image = resized(source, scale)
    box = solid_box(image)
    if 'skull' not in mark:
        x, y = SIZE / 2 - (box[0] + box[2]) / 2, REG['ground'] - box[3]
    x, y = round(x), round(y)
    frame = Image.new('RGBA', (SIZE, SIZE))
    frame.alpha_composite(image, (x, y))
    rear = foot_runs(image, box, SOLE_BAND)[0]
    return frame, (rear[0] + rear[1]) / 2 + x, sole_width(image), box[2] + x


def layout():
    """Registered frames and the CSS shift that plants every drawing on the idle rear sole.

    Every drawing is centred in its own canvas so long chains fit; the shift puts its rear
    sole back where the idle rear sole stands, so Kratos never slides while he is out. The
    contact drawings are drawn to one reach, so planting them also lines up the blade tips.
    """
    kept = {name: place(name) for name, mark in REG['poses'].items() if 'skull' in mark}
    kept_sole = statistics.median(sole for _, _, sole, _ in kept.values())
    placed = {name: kept.get(name) or place(name, kept_sole) for name in REG['poses']}
    idle_rear = placed['idle'][1]
    offsets = {name: round(idle_rear - rear) for name, (_, rear, _, _) in placed.items()
               if 'skull' not in REG['poses'][name]}
    tips = [placed[name][3] + offsets[name] for name in REG['contactPoses']]
    assert max(tips) - min(tips) <= REG['contactTolerance'], f'contact reach differs: {tips}'
    # Blade-tip line from the actor centre, in multiples of the contained canvas edge on screen.
    contact_reach = round((sum(tips) / len(tips) - SIZE / 2) * REG['displayScale'] / SIZE, 4)
    return {name: frame for name, (frame, *_) in placed.items()}, offsets, contact_reach


def pct(ms):
    return f'{ms * 100 / REG["durationMs"]:.4f}'.rstrip('0').rstrip('.') + '%'


def visibility(name):
    """Opacity keyframes showing a drawing during each of its key intervals."""
    keys = REG['keys']
    times = [time for time, _ in keys] + [REG['durationMs']]
    shown, hidden = [], []
    for index, (start, pose) in enumerate(keys):
        if pose != name:
            continue
        end = times[index + 1]
        shown += [pct(start), pct(end - .01) if end < REG['durationMs'] else '100%']
        if start > 0:
            hidden.append(pct(start - .01))
        if end < REG['durationMs']:
            hidden.append(pct(end))
    if keys[0][1] != name:
        hidden.insert(0, '0%')
    if keys[-1][1] != name:
        hidden.append('100%')
    rules = [f'  {", ".join(hidden)} {{ opacity: 0; }}'] if hidden else []
    return [f'@keyframes kratos-{"ready" if name == "idle" else name} {{',
            *rules, f'  {", ".join(shown)} {{ opacity: 1; }}', '}']


def combo_css(offsets):
    duration = REG['durationMs']
    (out_start, out_end), (back_start, back_end) = REG['timing']['travel']['out'], REG['timing']['travel']['back']
    # A contained square canvas maps one canvas pixel to min(width, height) * displayScale / canvas.
    factor = round(100 * REG['displayScale'] / SIZE, 6)
    names = list(dict.fromkeys(name for _, name in REG['keys']))
    lines = [CSS_START,
             '.character-attack--kratos {',
             '  container-type: size;',
             '  will-change: transform;',
             f'  animation: kratos-blade-travel {duration}ms ease-in-out both;',
             '}',
             '@keyframes kratos-blade-travel {',
             f'  0%, {pct(out_start)}, {pct(back_end)}, 100% {{ transform: translate(0); }}',
             f'  {pct(out_end)}, {pct(back_start)} {{ transform: translate(var(--attack-x), var(--attack-y)); }}',
             '}',
             '.character-attack--kratos .character-attack__pose {',
             f'  translate: calc(var(--kratos-pose-x, 0) * min(1cqw, 1cqh) * {factor}) 0;',
             '}']
    for name in names:
        css_name = 'ready' if name == 'idle' else name
        shift = f' --kratos-pose-x: {offsets[name]};' if name in offsets else ''
        lines.append(f'.character-attack__pose--kratos-{css_name} {{ animation: kratos-{css_name} {duration}ms linear both;{shift} }}')
    for name in names:
        lines += visibility(name)
    return '\n'.join(lines + [CSS_END])


def ms(value):
    return f'{value:_}'


def timing_ts(contact_reach):
    onset = {name: time for time, name in reversed(REG['keys'])}
    hits = ', '.join(ms(onset[name]) for name in REG['timing']['hitPoses'])
    cues = ', '.join(ms(onset[name]) for name in REG['timing']['chainCuePoses'])
    poses = ', '.join(repr('ready' if name == 'idle' else name) for name in dict.fromkeys(name for _, name in REG['keys']))
    return '\n'.join([TS_START,
                      f'export const KRATOS_ATTACK_MS = {ms(REG["durationMs"])}',
                      '/** The registered drawings are baked with this much transparent overscan. */',
                      f'export const KRATOS_DISPLAY_SCALE = {REG["displayScale"]}',
                      '/** Both light hits and the slam share one blade-tip line, this many contained',
                      ' * canvas edges right of the actor centre. */',
                      f'export const KRATOS_CONTACT_REACH = {contact_reach}',
                      f'const KRATOS_HIT_MS = [{hits}] as const',
                      f'export const KRATOS_CHAIN_CUE_MS = [{cues}] as const',
                      '/** Every registered drawing, by its runtime file name. */',
                      f'export const KRATOS_POSES = [{poses}] as const',
                      TS_END])


def write_generated(offsets, contact_reach):
    """Keep the CSS clock, pose shifts and the travel's timing constants in step with the drawings."""
    css_block = re.compile(re.escape(CSS_START) + '.*?' + re.escape(CSS_END), re.S)
    ts_block = re.compile(re.escape(TS_START) + '.*?' + re.escape(TS_END), re.S)
    css, vfx = CSS.read_text(), VFX.read_text()
    assert css_block.search(css), 'attack-timing.css lost its generated Kratos block'
    assert ts_block.search(vfx), 'vfx.tsx lost its generated Kratos timing block'
    new_css = css_block.sub(lambda _: combo_css(offsets), css)
    new_vfx = ts_block.sub(lambda _: timing_ts(contact_reach), vfx)
    if '--check' in sys.argv:
        assert (new_css, new_vfx) == (css, vfx), 'Kratos CSS or timing constants are stale; rerun kratos.py'
        print('PASS: Kratos clock, pose offsets and timing constants match the registered drawings')
        return
    CSS.write_text(new_css)
    VFX.write_text(new_vfx)


def sway(frame, angle):
    return frame.rotate(angle, Image.Resampling.BICUBIC, center=(SIZE / 2, REG['ground']))


def save(path, frames, durations, loop, *, method=6):
    path.parent.mkdir(parents=True, exist_ok=True)
    for frame in frames:
        box = solid_box(frame)
        assert box and min(box[0], box[1], SIZE - box[2], SIZE - box[3]) >= 4, (path, box)
    assert min(durations) >= 20, 'Browsers stretch frames shorter than 20ms'
    frames[0].save(path, save_all=True, append_images=frames[1:], duration=durations,
                   loop=loop, quality=88, method=method)
    print(f'{path.relative_to(ROOT)}: {len(frames)} frames, {sum(durations)}ms')


def main():
    poses, offsets, contact_reach = layout()
    write_generated(offsets, contact_reach)
    if '--check' in sys.argv:
        return
    idle = poses['idle']
    # Eight slow, rigid sway drawings keep stature and blade length constant.
    idle_frames = [sway(idle, .3 * math.sin(i * math.tau / 8)) for i in range(8)]
    save(OUT / 'animated/kratos-idle.webp', idle_frames, [400] * 8, 0)
    keys = [(time, name) for time, name in REG['keys']]
    assert len(keys) <= 20, 'User keyframe budget'
    times = [time for time, _ in keys]
    durations = [b - a for a, b in zip(times, times[1:] + [REG['durationMs']])]
    assert sum(durations) == REG['durationMs']
    assert keys[0][1] == keys[-1][1] == 'idle'
    # This unshipped review preview applies the on-screen shifts on a wider canvas.
    pad = -min(0, *offsets.values())
    preview = []
    for _, name in keys:
        frame = Image.new('RGBA', (SIZE + pad + max(0, *offsets.values()), SIZE))
        frame.alpha_composite(poses[name], (pad + offsets.get(name, 0), 0))
        preview.append(frame)
    (ROOT / 'artifacts/kratos-art').mkdir(parents=True, exist_ok=True)
    preview[0].save(ROOT / 'artifacts/kratos-art/kratos-attack.webp', save_all=True, append_images=preview[1:],
                    duration=durations, loop=0, quality=80, method=1)
    for name, pose in poses.items():
        pose.save(OUT / f'animated/kratos-{"ready" if name == "idle" else name}.webp', quality=88, method=6)
    # Inverse overscan gives reduced motion the same on-screen stature as idle.
    edge = round(SIZE * REG['displayScale'])
    full = idle.resize((edge, edge), Image.Resampling.LANCZOS)
    left, top = (edge - SIZE) // 2, edge - SIZE
    hero = full.crop((left, top, left + SIZE, edge))
    hero.save(OUT / 'kratos-hero.webp', quality=92, method=6)
    hero.resize((512, 512), Image.Resampling.LANCZOS).save(OUT / 'kratos.webp', quality=90, method=6)
    vfx = ROOT / 'public/assets/combat/vfx/actions/kratos'
    vfx.mkdir(parents=True, exist_ok=True)
    for name in ['light', 'impact']:
        Image.open(ROOT / REG['vfx'][name]).resize((512, 512), Image.Resampling.LANCZOS).save(
            vfx / f'{name}.webp', quality=88, method=6)
    # A contrasting contact sheet makes every delivered drawing reviewable.
    sheet = Image.new('RGBA', (SIZE * 5, SIZE * math.ceil(len(poses) / 5)), '#15556c')
    for i, pose in enumerate(poses.values()):
        sheet.alpha_composite(pose, ((i % 5) * SIZE, (i // 5) * SIZE))
    sheet.convert('RGB').save(ROOT / 'artifacts/kratos-art/registered-keyframes.jpg')


if __name__ == '__main__':
    main()
